---
#This task is to create svcansible user
#
- hosts: syslogclient
  become: true
  tasks:
    - name: Add the user 'Tnj'
      user:
        name: tnj
        comment: tnj local user
        state: present

    - name: disable account expire and set password aging to max...
      shell:
        chage -m 0 -M 99999 -I -1 -E -1 tnj

    - name: ssh key push
      authorized_key:
              user: tnj
              state: present
              key: "{{ lookup('file', '/home/svcansible/.ssh/id_rsa.pub') }}"
    - name: Allow passwordless sudo
      lineinfile:
              dest: /etc/sudoers
              state: present
#              regexp: '^%wheel\s'
              line: 'tnj            ALL=(ALL) NOPASSWD: ALL'
